
name: Deploy static content to Pages
on:
  push:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password  
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 13.83.8.217
          username: ubuntu
          Password: Facebook@0911
          port: 22

      - name: test
        run: |
          cd /home/ubuntu/delete-user
          git pull origin main
          chmod a+x delete-user.sh
          bash delete-user.sh user.txt
