
name: Deploy static content to Pages
on:
  push:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: 13.83.8.217
          username: ubuntu
          Password: Facebook@0911
          port: 22
          
          script: |
            sudo -i
            cd /home/ubuntu/
            git pull origin main 
            ./delete-user.sh user.txt
