
name: Deploy static content to Pages
on:
  push:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password  
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 13.83.8.217
          username: ubuntu
          Password: Facebook@0911
          port: 22
          source: "delete-user.sh,user.txt"
          target: /home/ubuntu/
      - name: test   
        run: | 
          sudo chmod a+x /home/ubuntu/delete-user.sh
          bash /home/ubuntu/delete-user.sh user.txt
